/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.awt.Color;

/**
 *
 * @author cesar
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        getContentPane().setBackground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labFicha11 = new javax.swing.JLabel();
        labFicha12 = new javax.swing.JLabel();
        labFicha13 = new javax.swing.JLabel();
        labFicha14 = new javax.swing.JLabel();
        labFicha15 = new javax.swing.JLabel();
        labFicha16 = new javax.swing.JLabel();
        labFicha17 = new javax.swing.JLabel();
        labFicha21 = new javax.swing.JLabel();
        labFicha22 = new javax.swing.JLabel();
        labFicha23 = new javax.swing.JLabel();
        labFicha24 = new javax.swing.JLabel();
        labFicha25 = new javax.swing.JLabel();
        labFicha26 = new javax.swing.JLabel();
        labFicha27 = new javax.swing.JLabel();
        labFicha31 = new javax.swing.JLabel();
        labFicha32 = new javax.swing.JLabel();
        labFicha33 = new javax.swing.JLabel();
        labFicha34 = new javax.swing.JLabel();
        labFicha35 = new javax.swing.JLabel();
        labFicha36 = new javax.swing.JLabel();
        labFicha37 = new javax.swing.JLabel();
        labFicha41 = new javax.swing.JLabel();
        labFicha42 = new javax.swing.JLabel();
        labFicha43 = new javax.swing.JLabel();
        labFicha44 = new javax.swing.JLabel();
        labFicha45 = new javax.swing.JLabel();
        labFicha46 = new javax.swing.JLabel();
        labFicha47 = new javax.swing.JLabel();
        labFicha51 = new javax.swing.JLabel();
        labFicha52 = new javax.swing.JLabel();
        labFicha53 = new javax.swing.JLabel();
        labFicha54 = new javax.swing.JLabel();
        labFicha55 = new javax.swing.JLabel();
        labFicha56 = new javax.swing.JLabel();
        labFicha57 = new javax.swing.JLabel();
        labFicha61 = new javax.swing.JLabel();
        labFicha62 = new javax.swing.JLabel();
        labFicha63 = new javax.swing.JLabel();
        labFicha64 = new javax.swing.JLabel();
        labFicha65 = new javax.swing.JLabel();
        labFicha66 = new javax.swing.JLabel();
        labFicha67 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jLabel6.setText("jLabel6");

        jLabel32.setText("jLabel32");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(6, 7));
        jPanel1.add(labFicha11);
        jPanel1.add(labFicha12);
        jPanel1.add(labFicha13);
        jPanel1.add(labFicha14);
        jPanel1.add(labFicha15);
        jPanel1.add(labFicha16);
        jPanel1.add(labFicha17);

        labFicha21.setText("imagenes");
        jPanel1.add(labFicha21);

        labFicha22.setText("de");
        jPanel1.add(labFicha22);

        labFicha23.setText("fichas");
        jPanel1.add(labFicha23);
        jPanel1.add(labFicha24);
        jPanel1.add(labFicha25);
        jPanel1.add(labFicha26);
        jPanel1.add(labFicha27);
        jPanel1.add(labFicha31);
        jPanel1.add(labFicha32);
        jPanel1.add(labFicha33);
        jPanel1.add(labFicha34);
        jPanel1.add(labFicha35);
        jPanel1.add(labFicha36);
        jPanel1.add(labFicha37);
        jPanel1.add(labFicha41);
        jPanel1.add(labFicha42);
        jPanel1.add(labFicha43);
        jPanel1.add(labFicha44);
        jPanel1.add(labFicha45);
        jPanel1.add(labFicha46);
        jPanel1.add(labFicha47);
        jPanel1.add(labFicha51);
        jPanel1.add(labFicha52);
        jPanel1.add(labFicha53);
        jPanel1.add(labFicha54);
        jPanel1.add(labFicha55);
        jPanel1.add(labFicha56);
        jPanel1.add(labFicha57);
        jPanel1.add(labFicha61);
        jPanel1.add(labFicha62);
        jPanel1.add(labFicha63);
        jPanel1.add(labFicha64);
        jPanel1.add(labFicha65);
        jPanel1.add(labFicha66);
        jPanel1.add(labFicha67);

        jLabel1.setFont(new java.awt.Font("Dubai Medium", 1, 24)); // NOI18N
        jLabel1.setText("CONNECT 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(196, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JLabel labFicha11;
    public javax.swing.JLabel labFicha12;
    public javax.swing.JLabel labFicha13;
    public javax.swing.JLabel labFicha14;
    public javax.swing.JLabel labFicha15;
    public javax.swing.JLabel labFicha16;
    public javax.swing.JLabel labFicha17;
    public javax.swing.JLabel labFicha21;
    public javax.swing.JLabel labFicha22;
    public javax.swing.JLabel labFicha23;
    public javax.swing.JLabel labFicha24;
    public javax.swing.JLabel labFicha25;
    public javax.swing.JLabel labFicha26;
    public javax.swing.JLabel labFicha27;
    public javax.swing.JLabel labFicha31;
    public javax.swing.JLabel labFicha32;
    public javax.swing.JLabel labFicha33;
    public javax.swing.JLabel labFicha34;
    public javax.swing.JLabel labFicha35;
    public javax.swing.JLabel labFicha36;
    public javax.swing.JLabel labFicha37;
    public javax.swing.JLabel labFicha41;
    public javax.swing.JLabel labFicha42;
    public javax.swing.JLabel labFicha43;
    public javax.swing.JLabel labFicha44;
    public javax.swing.JLabel labFicha45;
    public javax.swing.JLabel labFicha46;
    public javax.swing.JLabel labFicha47;
    public javax.swing.JLabel labFicha51;
    public javax.swing.JLabel labFicha52;
    public javax.swing.JLabel labFicha53;
    public javax.swing.JLabel labFicha54;
    public javax.swing.JLabel labFicha55;
    public javax.swing.JLabel labFicha56;
    public javax.swing.JLabel labFicha57;
    public javax.swing.JLabel labFicha61;
    public javax.swing.JLabel labFicha62;
    public javax.swing.JLabel labFicha63;
    public javax.swing.JLabel labFicha64;
    public javax.swing.JLabel labFicha65;
    public javax.swing.JLabel labFicha66;
    public javax.swing.JLabel labFicha67;
    // End of variables declaration//GEN-END:variables
}
